version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-starwars
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: starwars
    ports:
      - "3309:3306"
    restart: no
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
